# Generated by Django 5.0.3 on 2024-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="articles_likes", to="user.user"
            ),
        ),
    ]
